import React from 'react';

export const VERSION = "1.0.0";

export const MONTHS = {
    1: 'Gener',
    2: 'Febrer',
    3: 'Març',
    4: 'Abril',
    5: 'Maig',
    6: 'Juny',
    7: 'Juliol',
    8: 'Agost',
    9: 'Setembre',
    10: 'Octubre',
    11: 'Novembre',
    12: 'Desembre'
};

export const BASIC_AUTH_REQUEST = 'BASIC_AUTH_REQUEST';
export const BASIC_AUTH_RESPONSE = 'BASIC_AUTH_RESPONSE';
export const BASIC_AUTH_ERROR = 'BASIC_AUTH_ERROR';
export const SET_TOKEN = 'SET_TOKEN';
export const LOGOUT = 'LOGOUT';

export const UI_OPEN_MENU = 'UI_OPEN_MENU';
export const UI_CLOSE_MENU = 'UI_CLOSE_MENU';

export const BREADCRUMB_ADD = 'BREADCRUMB_ADD';
export const BREADCRUMB_CLEAR = 'BREADCRUMB_CLEAR';

export const RECEIVE_PROJECTS = 'RECEIVE_PROJECTS';
export const FETCH_PROJECTS_REQUEST = 'FETCH_PROJECTS_REQUEST';
export const SET_ACTIVE_PROJECT = 'SET_ACTIVE_PROJECT';
export const CREATE_PROJECT_REQUEST = 'CREATE_PROJECT_REQUEST';
export const CREATE_PROJECT_RESPONSE = 'CREATE_PROJECT_RESPONSE';
export const EDIT_PROJECT = 'EDIT_PROJECT';
export const PATCH_PROJECT_REQUEST = 'PATCH_PROJECT_REQUEST';
export const PATCH_PROJECT_RESPONSE = 'PATCH_PROJECT_RESPONSE';

export const RECEIVE_TASKS = 'RECEIVE_TASKS';
export const FETCH_TASKS_REQUEST = 'FETCH_TASKS_REQUEST';
export const SET_ACTIVE_TASK = 'SET_ACTIVE_TASK';
export const CREATE_TASK_REQUEST = 'CREATE_TASK_REQUEST';
export const CREATE_TASK_RESPONSE = 'CREATE_TASK_RESPONSE';
export const EDIT_TASK = 'EDIT_TASK';
export const PATCH_TASK_REQUEST = 'PATCH_TASK_REQUEST';
export const PATCH_TASK_RESPONSE = 'PATCH_TASK_RESPONSE';
export const OPEN_TASK_REQUEST = 'OPEN_TASK_REQUEST';
export const OPEN_TASK_RESPONSE = 'OPEN_TASK_RESPONSE';

export const SEARCH_PROJECTS_REQUEST = 'SEARCH_PROJECTS_REQUEST';

export const SEARCH_TASKS_REQUEST = 'SEARCH_TASKS_REQUEST';

export const SEARCH_USERS_REQUEST = 'SEARCH_USERS_REQUEST';

export const SEARCH_COMPANIES_REQUEST = 'SEARCH_COMPANIES_REQUEST';

export const RECEIVE_TASK_WORK = 'RECEIVE_TASK_WORK';
export const FETCH_TASK_WORK_REQUEST = 'FETCH_TASK_WORK_REQUEST';
export const CREATE_TASK_WORK_REQUEST = 'CREATE_TASK_WORK_REQUEST';
export const CREATE_TASK_WORK_RESPONSE = 'CREATE_TASK_WORK_RESPONSE';
export const PATCH_TASK_WORK_REQUEST = 'PATCH_TASK_WORK_REQUEST';
export const PATCH_TASK_WORK_RESPONSE = 'PATCH_TASK_WORK_RESPONSE';
export const DELETE_TASK_WORK_REQUEST = 'DELETE_TASK_WORK_REQUEST';
export const DELETE_TASK_WORK_RESPONSE = 'DELETE_TASK_WORK_RESPONSE';
export const GET_TASKS_STATUS_REQUEST = 'GET_TASKS_STATUS_REQUEST';
export const GET_TASKS_STATUS_RESPONSE = 'GET_TASKS_STATUS_RESPONSE';
export const GET_USER_TASKS_COUNT_REQUEST = 'GET_USER_TASKS_COUNT_REQUEST';
export const GET_USER_TASKS_COUNT_RESPONSE = 'GET_USER_TASKS_COUNT_RESPONSE';
export const GET_STARTED_TASKS_COUNT_REQUEST = 'GET_STARTED_TASKS_COUNT_REQUEST';
export const GET_STARTED_TASKS_COUNT_RESPONSE = 'GET_STARTED_TASKS_COUNT_RESPONSE';

export const RECEIVE_USERS = 'RECEIVE_USERS';
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const SHOW_ALL_USER_TASKS_FLAG = 'SHOW_ALL_USER_TASKS_FLAG';

export const RECEIVE_COMPANIES = 'RECEIVE_COMPANIES';
export const FETCH_COMPANIES_REQUEST = 'FETCH_COMPANIES_REQUEST';
export const SET_ACTIVE_COMPANY = 'SET_ACTIVE_COMPANY';

export const SET_FILTERS = 'SET_FILTERS';
export const ADD_FILTER = 'ADD_FILTER';

export const SET_ITEMS_PER_PAGE = 'SET_ITEMS_PER_PAGE';
export const SET_ACTUAL_PAGE = 'SET_ACTUAL_PAGE';

export const UI_OPEN_DIALOG = 'UI_OPEN_DIALOG';
export const UI_CLOSE_DIALOG = 'UI_CLOSE_DIALOG';

export const UI_OPEN_FILTER_BUTTON_MENU = 'UI_OPEN_FILTER_BUTTON_MENU';
export const UI_CLOSE_FILTER_BUTTON_MENU = 'UI_CLOSE_FILTER_BUTTON_MENU';

export const UI_OPEN_TOAST = 'UI_OPEN_TOAST';
export const UI_CLOSE_TOAST = 'UI_CLOSE_TOAST';

export const UI_NEW_EDIT_ITEM = 'UI_NEW_EDIT_ITEM';

export const UI_SET_FIELDS_ERROR = 'UI_SET_FIELDS_ERROR';

export const SET_DAZZLE_STATE = 'SET_DAZZLE_STATE';